version: "3.7"
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ..:/api
    depends_on:
      - db
    command: /bin/sh -c "go mod tidy -compat=1.17 && air -c .air.toml"
    image: go-gin-gorm-sample-api
    container_name: go-gin-gorm-sample-api
    environment:
      POSTGRES_URL: "postgres://user:password@db:5432/database?sslmode=disable"
  db:
    build: ./db
    restart: always
    environment:
      POSTGRES_DB: 'database'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5433:5432"
    volumes:
      - go_gin_gorm_sample_db_data:/var/lib/postgresql/data
    image: go-gin-gorm-sample-db
    container_name: go-gin-gorm-sample-db
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8001:8080
    volumes:
      - ../openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
volumes:
  go_gin_gorm_sample_db_data:
