version: "3.7"
services: 
    app:
        build: ./docker/app
        tty: true
        ports:
            - "8080:8080"
        volumes:
            - ./src:/go/src
        depends_on: 
            - db
        command: /bin/sh -c "go mod tidy && air -c .air.toml"
    db:
        image: mysql:8.0.27
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=database
            - MYSQL_ROOT_PASSWORD=password
volumes:
  db_data: